local min_x = 16
local min_y = 16
local max_x = tonumber(sys.get_config("display.width")) - 16
local max_y = tonumber(sys.get_config("display.height")) - 16

function init(self)
	local spawnP = vmath.vector3()

	repeat
		spawnP = vmath.vector3(math.random(min_x, max_x),math.random(min_y,max_y), 0)
	until(spawnP.x ~= 320  and spawnP.y ~= 240)

	print(spawnP)
	factory.create("#candy_factory", spawnP)
end